version: "3.8"
services:
  app:
    build: .
    container_name: cinema-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: cinema-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cinema
      MYSQL_USER: cinemauser
      MYSQL_PASSWORD: cinemapass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
