version: "3.8"

services:
  app:
    build: .
    container_name: cinema-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - cinema

  db:
    image: mysql:8.0
    container_name: cinema-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cinema
      MYSQL_USER: cinemauser
      MYSQL_PASSWORD: cinemapass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cinema

volumes:
  dbdata:

networks:
  cinema:
