version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USER:-local}/cinema-backend:latest
    container_name: cinema-app
    restart: unless-stopped
    ports:
      - "80:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: cinema
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    depends_on:
      - db
    volumes:
      - ./.env:/var/www/.env              # mount host .env (must exist)
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache

  db:
    image: mysql:8.0
    container_name: cinema-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cinema
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - cinema-db-data:/var/lib/mysql

volumes:
  cinema-db-data: