name: Deploy to EC2 (Cinema Backend)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Check disk space
            df -h
            
            # Clean up Docker to free space
            docker system prune -af --volumes
            docker image prune -af
            
            # Remove old containers and images
            docker container prune -f
            docker volume prune -f
            
            # Create directory if not exists
            if [ ! -d "~/cinema-backend" ]; then
              git clone https://github.com/amayones/ujikom-be-ac.git ~/cinema-backend
            fi
            
            # Navigate to project directory
            cd ~/cinema-backend
            
            # Update code
            git stash
            git pull origin main
            
            # Setup environment if not exists
            if [ ! -f ".env" ]; then
              cp .env.production .env
            fi
            
            # Create SSL directory if not exists
            mkdir -p nginx/ssl
            
            # Check if SSL certificates exist, if not use HTTP deployment
            if [ -f "/etc/letsencrypt/live/be-ujikom.amayones.my.id/fullchain.pem" ]; then
              echo "SSL certificates found, deploying with HTTPS..."
              sudo cp /etc/letsencrypt/live/be-ujikom.amayones.my.id/fullchain.pem ./nginx/ssl/cert.pem
              sudo cp /etc/letsencrypt/live/be-ujikom.amayones.my.id/privkey.pem ./nginx/ssl/key.pem
              sudo chown ubuntu:ubuntu ./nginx/ssl/*.pem
              docker compose -f docker-compose.ssl.yml down --remove-orphans
              docker compose -f docker-compose.ssl.yml up -d --build
            else
              echo "SSL certificates not found, deploying with HTTP..."
              docker compose down --remove-orphans
              docker compose up -d --build
            fi