name: Deploy Cinema

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Copy files to server
uses: appleboy/scp-action@v0.1.5
with:
host: ${{ secrets.LIGHTSAIL_IP }}
username: ubuntu
key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
source: "."
target: "/home/ubuntu/cinema"
- name: SSH commands
uses: appleboy/ssh-action@v0.1.6
with:
host: ${{ secrets.LIGHTSAIL_IP }}
username: ubuntu
key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
script: |
cd /home/ubuntu/cinema
cp .env.example .env
docker-compose down
docker-compose up -d --build
docker exec -it cinema-app bash -c "php artisan key:generate && php artisan migrate --seed"