name: Deploy to EC2 (Cinema Backend)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/cinema-backend
            git stash
            git pull origin main
            docker compose -f docker-compose.ssl.yml down --remove-orphans
            docker compose -f docker-compose.ssl.yml up -d --build