name: Deploy Cinema to AWS Lightsail

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.LIGHTSAIL_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
          cd /home/ubuntu/cinema
          
          # Pull latest changes
          git pull origin main
          
          # Stop containers
          docker-compose down
          
          # Rebuild and start
          docker-compose build --no-cache
          docker-compose up -d
          
          # Wait for containers
          sleep 30
          
          # Laravel setup
          docker exec cinema-app php artisan config:cache
          docker exec cinema-app php artisan route:cache
          docker exec cinema-app php artisan migrate --force
          
          # Set permissions
          docker exec cinema-app chown -R www-data:www-data /var/www/storage
          docker exec cinema-app chmod -R 755 /var/www/storage
          
          echo "✅ Deployment completed successfully!"
        EOF
