name: Deploy Cinema

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/cinema"

      - name: SSH commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/ubuntu/cinema
            if [ ! -f .env ]; then
                cp .env.example .env
            fi
            sudo chown -R www-data:www-data /home/ubuntu/cinema
            sudo chmod -R 755 /home/ubuntu/cinema
            docker-compose down
            docker-compose up -d --build
            sleep 15
            docker exec cinema-app php artisan key:generate
            docker exec cinema-app php artisan migrate --seed
            echo "✅ Deploy selesai, Laravel sudah siap!"
